#!/bin/bash

# Virtual environment of python copy required python in a predefined folder and if environment activated all dependencies will be installed in this folder and python in this folder will be used 

# Prerequisites
sudo apt update && sudo apt upgrade
sudo apt-get install wget build-essential checkinstall
sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev \
    libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev

# Step 1 : download and setup required python version : for example version=3.7.12
cd /usr/src
sudo wget https://www.python.org/ftp/python/3.7.12/Python-3.7.12.tgz
sudo tar xzf Python-3.7.9.tgz
cd Python-3.7.12
sudo ./configure --enable-optimizations
sudo make altinstall
python3.7 -V            # must print Python-3.7.12
cd environment dir
#deactivate conda if activated 
conda deactivate
virtualenv --python=python3.7 envName
# activate new env
source ./envName/bin/activate
#To deactivate just type ->  deactivate
